# Generated by Django 5.1.8 on 2025-04-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_task_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#808080', max_length=20),
        ),
    ]
